### ISSUE TITLE
Cloud Databases - 413 while respecting limits

### ISSUE THREAD

**Issue by jeffcasavant** [rackspace/pyrax#526]
I'm using Pyrax to back up all of my cloud databases.  Recently we added a sixth cloud DB instance, and our backup script began to throw the 413 exception (OverLimit).

I believe I'm respecting the limits (100/min on this particular endpoint, and 25/min or 2/sec on POST endpoints in general) - this script should generate 1 request per two seconds, for a total of six.

The relevant code:

```
databases = cloud_databases.list()

for db in databases:
        if db.status.upper() != 'ACTIVE':
            print 'Did not run backup on %s: Status was %s' % (db.name, db.status)
            continue

        backupName = '%s-%s' % (db.name, dateString)
        backup = db.create_backup(backupName)
        print 'Successfully created backup %s' % backupName

        # Respect rate limits
        sleep(2)
```

**Comment by briancurtin** [comment]
This is something you should take up with the actual Rackspace support as pyrax itself doesn't do anything around limits except tell you when the server says you're over them. It doesn't look like you did anything wrong on the pyrax end of things, and the `sleep(2)` should certainly have respected the 2/sec limit.

I hate to suggest bumping up sleep times, but as a quick workaround, does a sleep of 3 or 4 seconds make a positive difference? If it doesn't and/or you don't want to do that in your code, that info should be helpful to support.

**Comment by jeffcasavant** [comment]
I tested it with a 10 second sleep time, and I got the same failure.  I'll contact support.  Thanks!
