### ISSUE TITLE
doxygen configuration references out of project file

### ISSUE THREAD

**Issue by alunduil** [rackspace/pyrax#556]
Hey,

Looks like the filter utility in the doxygen configuration references a file that's not in the source repository:

https://github.com/rackspace/pyrax/blob/v1.9.4/docs/dox.cfg#L742

Can we get that script added to the repository so we can build the documentation from the source if desired for packaging?

**Comment by sivel** [comment]
I'm afraid I don't actually have access to that file and it is no longer available.

**Comment by alunduil** [comment]
Wouldn't it be better to just fix the documentation so that file isn't necessary?

**Comment by EdLeafe** [comment]
That was for the godawful class docs that were initially required for all SDKs. When they dropped that requirement, we abandoned doxygen class docs. The dox.cfg file should be removed.

**Comment by alunduil** [comment]
Excellent.  Thanks for clearing that up @EdLeafe!
