### ISSUE TITLE
Bulk upload causes DDOS to DNS server

### ISSUE THREAD

**Issue by danpilch** [rackspace/pyrax#562]
When calling the  'store_object' function in multithreaded loops causes an insane amount of DNS requests for 'storage101.lon3.clouddrive.com' after a couple of hours the DNS server blocked all requests. This caused my uploads to lock. 

Pyrax shouldn't really be looking up the address every time.

**Comment by sivel** [comment]
DNS resolution in python is handled by `getaddrinfo()` which does not perform any caching.  The recommended way to handle DNS caching would be at the operating system level via a package such as nscd or similar.
