### ISSUE TITLE
Provide guidance on pyrax being deprecated 

### ISSUE THREAD

**Issue by linusnorton** [rackspace/pyrax#583]
Nearly 5 months ago this project was marked as deprecated with a notice saying guidance for using OpenStack instead will be provide. Given there are a large number of people using the module and Ansible also uses this module could you provide an update stating how people should use the OpenStack API in place of this repository. What are the timescales for depreciating this library, has all development stopped? Will bug fixes be put in place?

**Comment by sivel** [comment]
@linusnorton In regards to a timeframe for the openstacksdk being ready, we recently responded on another issue with some detailed information around that, which can be found at https://github.com/rackspace/pyrax/issues/582#issuecomment-152035640

As for bug fixes to pyrax, it is likely that only critical bug fixes affecting ansible or a large subset of users will make it in.

As for Ansible, I am one of the maintainers of pyrax, and a committer to Ansible and owner of the rax related modules in Ansible.  Until such a time when the modules can be updated to use the openstacksdk, or be deprecated and replaced, I will ensure that the rax modules in ansible continue to function.

The likely scenario with the rax modules in ansible is that they will be replaced and deprecated by `rackspace` prefixed modules that have different dependencies and after the course of several releases of ansible the `rax` prefixed modules will be removed.

**Comment by linusnorton** [comment]
Thanks for the update. I thought it might be a case of using the os modules when Ansible 2.0 is released  but it's good to know there will still be rackspace modules.
