### ISSUE TITLE
Release 1.9.5 does not include changes described in release notes

### ISSUE THREAD

**Issue by TDaglis** [rackspace/pyrax#592]
From the [release notes](https://github.com/rackspace/pyrax/blob/v1.9.5/RELEASENOTES.md), I would expect to see an updated `setup.py` with the pinned version of novaclient and the suppression of warnings.

> ### 2015.09.02 - Version 1.9.5
> 
>   - Cloud Servers
>    - Handle a change to python-novaclient 2.27.0
>    - Pin python-novaclient to less or equal to 2.27.0
>    - Suppress deprecation warnings emitted for novaclient.v1_1

After searching a bit, I found that this is done in this commit
https://github.com/briancurtin/pyrax/commit/e5d22a1bd6102f65b988af16c68c93d88b087b9b
which was merged in this PR https://github.com/rackspace/pyrax/pull/574

Shouldn't this be included in the 1.9.5 release as well?

**Comment by briancurtin** [comment]
Should have been, not sure why it wasn't. I'll look at re-releasing.

**Comment by briancurtin** [comment]
This was fixed in pyrax 1.9.6. It was supposed to have already been fixed in 1.9.5 but somehow the code to fix it wasn't properly merged into what got released.

**Comment by TDaglis** [comment]
:+1:
