### ISSUE TITLE
New novaclient breaks pyrax - removal of v1_1 support

### ISSUE THREAD

**Issue by BobBall** [rackspace/pyrax#593]
New novaclient was released on Friday which removes novaclient v1_1 support - as such, pyrax is currently unusable.

http://paste.openstack.org/show/482405/

https://review.openstack.org/gitweb?p=openstack/python-novaclient.git;a=commitdiff;h=f7e2129f887fe9925240ac8f63befdc7e3f01aa1

**Comment by briancurtin** [comment]
This was fixed in pyrax 1.9.6. It was supposed to have already been fixed in 1.9.5 but somehow the code to fix it wasn't properly merged into what got released.
