### ISSUE TITLE
pyrax does not respect prefixes in service catalog endpoints

### ISSUE THREAD

**Issue by rsyed83** [rackspace/pyrax#595]
A future release of Rackspace Managed DNS, based on Openstack Designate, will require an Identity service catalog endpoint of type "dns".  As Rackspace's current Cloud DNS product already reserves type "rax:dns", there should not be a conflict.

However pyrax does not seem to respect the "rax:" prefix in distinguishing one service from another.  While the prefix is separated during parsing of the service catalog, its value is not respected during service registration and conflicts can then occur:

https://github.com/rackspace/pyrax/blob/2bc45b387fbbced67fb993ca8331bc0eb0f0282d/pyrax/base_identity.py#L651

Sample service catalog with two dns endpoints:
https://gist.github.com/rsyed83/240c18ea10c6ff2a9503

Error returned by pyrax:
https://gist.github.com/rsyed83/3bfab6912fa02e094cbd

**Comment by sivel** [comment]
@rsyed83 thank you for the notification.

As pyrax is in feature freeze, I am going to recommend the following.  We should hardcode a check that ignores the new service, and only offers support for the current cloud dns.

I recommend this approach due to ansible relying on pyrax, and including DNS modules.

**Comment by briancurtin** [comment]
FWIW I referenced this bug on https://github.com/rackerlabs/rackspace-sdk-plugin/issues/23 so that when we add DNS support over there, we make sure this situation is covered.

**Comment by rsyed83** [comment]
@sivel and @briancurtin thanks for the quick replies.  I had worked on a "proper" fix for the issue, #597, but I understand it does require more widespread change and may not be desirable for software under feature freeze.  We can close it out if so.

#598 should cover the approach @sivel suggested, regarding hardcoding an exclusion.

**Comment by sivel** [comment]
I've merged #599 

As such, I'll go ahead and close this issue.

**Comment by rsyed83** [comment]
Thanks @sivel ! 

Any idea about timeframe for a minor release, so we could begin relying on a pypi artifact to address this issue?
