### ISSUE TITLE
RackConnect v3 Support

### ISSUE THREAD

**Issue by sumit-goel** [rackspace/pyrax#606]
Hi there, are there any plans to add RackConnect v3 support in pyrax? Or is there any other package that can be used for RackConnect v3?

**Comment by briancurtin** [comment]
It will not be added to Pyrax. It'll go in https://github.com/rackerlabs/rackspace-sdk-plugin

**Comment by sumit-goel** [comment]
Would you know when the RackConnect v3 support may be available in rackspace-sdk-plugin?

**Comment by briancurtin** [comment]
I am working on completing the upstream OpenStack SDK's 1.0 release first before getting into Rackspace specifics, so I don't have any estimates or exact plans yet.

**Comment by sumit-goel** [comment]
thanks @briancurtin
