### ISSUE TITLE
 Search for support-sdk@racksapce.com and remove

### ISSUE THREAD

**Issue by catlook** [rackspace/pyrax#621]
any found

**Comment by briancurtin** [comment]
What?

**Comment by catlook** [comment]
I plan to do it myself, Brian, but I’ve been asked to remove any occurrences of sdk-support@rackspace.com<mailto:sdk-support@rackspace.com> from our docs, including sdk docs.  If I find none, I’ll close the issue!

-- Cat Lookabaugh, Sr. Information Developer
Rackspace Hosting – the #1 Managed Cloud Company
Info Dev Team      cat.lookabaugh@rackspace.com
Office: (210) 312-8193   Cell: (210) 364-1060

**Comment by catlook** [comment]
OK, I'm assuming there are none and will move on.  Thanks, Brian!
